services:
  - type: web
    name: sql-compare
    env: python
    buildCommand: pip install .
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT sql_compare.web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
