services:
  - type: web
    name: sql-compare
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 sql_compare.web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
